# Description.
model_template_id: MobileNet-V3-small
name: MobileNet-V3-small
task_type: CLASSIFICATION
task_family: VISION
instantiation: "CLASS"
summary: Custom Image Classification MobileNet-V3-small
application:
  ~

# Algo backend.
framework: OTEClassification v1.2.3

# Task implementations.
entrypoints:
  base: torchreid.integration.sc.task.OTEClassificationTask
  openvino: torchreid.integration.sc.openvino_task.OpenVINOClassificationTask

# Hyperparameters.
hyper_parameters:
  base_path: "../../../torchreid/integration/sc/configuration.yaml"
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 30
      max_num_epochs:
        default_value: 200
      learning_rate:
        default_value: 0.001

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 0.12
size: 1.56
